//! Regenerate `docs/COMPATIBILITY.md` from compat runs.
//!
//! Inputs:
//!
//! * `compat/games.toml`         facts per disc (title, serial, region, hashes)
//! * `compat/observations.toml`  human judgement per disc: status tier (and the
//!   tier the recorded real-BIOS run reached), FMV status, known issues, the
//!   evidence behind them, and the final display hash of the run they were
//!   judged on
//! * `compat/reference.toml`     the last real-BIOS reference runs, recorded
//!   before BIOS support was removed
//! * one or more `hle_compat --json` reports (files or directories of them),
//!   normally a full `hle_compat --inputs compat/inputs.toml` run
//!
//! The runner measures what a machine can: whether the boot reached the
//! executable, how far it ran, the first unimplemented kernel call, whether the
//! last frame matches the recorded real-BIOS run, MDEC work, lost sectors,
//! LibCrypt subchannel data. Tiers need someone to look at frames, so they come
//! from `observations.toml`; when a new run's final display differs from the one
//! a tier was judged on, the table says the tier needs another look instead of
//! silently keeping it.
//!
//! Usage: `cargo run --release --manifest-path tools/compat-report/Cargo.toml --
//! <report.json|dir> [...] [--out docs/COMPATIBILITY.md] [--root <repo>]`
//!
//! `--root` defaults to the repository this tool lives in.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde_json::Value;

const TIERS: [&str; 7] = [
    "none", "boots", "intro", "menu", "in-game", "playable", "perfect",
];

const HEADER: &str = "# Compatibility

What runs on PSoXide. PSoXide boots every disc with its own clean-room HLE
kernel and needs no BIOS (it cannot use one). For comparison, the \"Real BIOS\"
column is a real-kernel run with the same input, recorded before BIOS
support was removed (`compat/reference.toml`). Generated by
`tools/compat-report` from `compat/games.toml`, `compat/observations.toml`,
`compat/reference.toml` and an `hle_compat` run; edit those, not this file. Game names and results only: no game data or
images live in this repository.

## Status tiers

| Tier | Meaning |
|---|---|
| none | Nothing useful on screen (black or a hang before the first picture). |
| boots | Reaches the game's executable and draws something of its own. |
| intro | Logos, legal screens, FMV or attract mode play. |
| menu | Title screen or menus respond to input. |
| in-game | Gameplay (or the game's own engine running past its menus, such as an opening cutscene after New Game) is reached with scripted input. |
| playable | Played through a real stretch by a person without game-breaking problems. |
| perfect | Played through with no known problems. |

Headless runs can show at most **in-game**: they press Start and Cross on a
fixed schedule and look at frames. **playable** and **perfect** need a
person (evidence \"Manny, console\" or \"Manny, GUI\").

FMV: **plays** (movies decode and show), **partial** (some movies or frames
missing), **broken**, **none seen** (none reached in the run), **n/a** (the
game has none).

## How the runs are made

`hle_compat --inputs compat/inputs.toml` boots each disc from the
executable's entry with a formatted empty memory card, a digital pad and no
frame limiter, for the run length and pad schedule `compat/inputs.toml`
gives it (games without one: Start at frame 600, Cross at 750, alternating
every 150 frames to 3450, for 3600 frames). The \"Real BIOS\" column comes
from the same runs made through the developer's own BIOS dump on
{ref_commits}, counted from the same point; \"Last frame = BIOS\" compares
this run's last frame with that recording. Frames were looked at for every
tier below.

Run on: {commits}
";

const COLUMNS: &str =
    "| | Game | Serial | Region | PSoXide | Real BIOS (recorded) | FMV | Known issues | \
Last frame = BIOS | Measured on | Evidence |";

type Table = toml::map::Map<String, toml::Value>;

/// One `hle_compat` result row plus the report it came from.
struct Run {
    result: Value,
    commit: Option<String>,
}

fn load_toml(path: &Path) -> Result<Table, String> {
    let text = fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    text.parse::<Table>()
        .map_err(|e| format!("{}: {e}", path.display()))
}

/// Python-style truthiness for a JSON value that may be absent.
fn truthy(v: Option<&Value>) -> bool {
    match v {
        None | Some(Value::Null) => false,
        Some(Value::Bool(b)) => *b,
        Some(Value::Number(n)) => n.as_f64().is_some_and(|f| f != 0.0),
        Some(Value::String(s)) => !s.is_empty(),
        Some(Value::Array(a)) => !a.is_empty(),
        Some(Value::Object(o)) => !o.is_empty(),
    }
}

/// `str(value)` for the scalar kinds that appear in the compat tables.
fn display(v: &toml::Value) -> String {
    match v {
        toml::Value::String(s) => s.clone(),
        toml::Value::Integer(i) => i.to_string(),
        toml::Value::Boolean(b) => if *b { "True" } else { "False" }.to_string(),
        other => other.to_string(),
    }
}

/// `str(value)` for a JSON scalar, as the report prints it in issue text.
fn json_display(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

fn load_reports(paths: &[String]) -> Result<(BTreeMap<String, Run>, BTreeSet<String>), String> {
    let mut results = BTreeMap::new();
    let mut commits = BTreeSet::new();
    let mut files: Vec<PathBuf> = Vec::new();
    for p in paths {
        let path = PathBuf::from(p);
        if path.is_dir() {
            let mut found: Vec<PathBuf> = fs::read_dir(&path)
                .map_err(|e| format!("{p}: {e}"))?
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|f| f.to_string_lossy().ends_with(".json"))
                .collect();
            found.sort();
            files.extend(found);
        } else {
            files.push(path);
        }
    }
    for f in files {
        let text = fs::read_to_string(&f).map_err(|e| format!("{}: {e}", f.display()))?;
        let report: Value =
            serde_json::from_str(&text).map_err(|e| format!("{}: {e}", f.display()))?;
        let schema = report.get("schema").map(json_display).unwrap_or_default();
        if !schema.starts_with("psoxide-hle-compat/") {
            continue;
        }
        let commit = match report.get("emulator_commit") {
            Some(c) if truthy(Some(c)) => Some(json_display(c)),
            _ => None,
        };
        if let Some(c) = &commit {
            commits.insert(c.clone());
        }
        for r in report
            .get("results")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            if r.get("status").and_then(Value::as_str) == Some("missing") {
                continue;
            }
            let id = r.get("id").map(json_display).unwrap_or_default();
            results.insert(
                id,
                Run {
                    result: r.clone(),
                    commit: commit.clone(),
                },
            );
        }
    }
    Ok((results, commits))
}

/// Escape one table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

fn get_str(t: &Table, key: &str) -> Option<String> {
    t.get(key).map(display)
}

fn table<'a>(t: &'a Table, key: &str) -> Option<&'a Table> {
    t.get(key).and_then(toml::Value::as_table)
}

fn run(inputs: &[String], out: &Path, root: &Path) -> Result<String, String> {
    let games_doc = load_toml(&root.join("compat/games.toml"))?;
    let obs = load_toml(&root.join("compat/observations.toml"))?;
    let reference = load_toml(&root.join("compat/reference.toml"))?;
    let games: &[toml::Value] = games_doc
        .get("game")
        .and_then(toml::Value::as_array)
        .map_or(&[], Vec::as_slice);
    let (results, commits) = load_reports(inputs)?;
    let empty = Table::new();

    let mut rows: Vec<String> = Vec::new();
    let mut notes: Vec<String> = Vec::new();
    for g in games {
        let g = g.as_table().ok_or("games.toml: [[game]] is not a table")?;
        let gid = get_str(g, "id").ok_or("games.toml: game without id")?;
        let o = table(&obs, &gid).unwrap_or(&empty);
        let found = results.get(&gid);
        for key in ["hle", "bios"] {
            if let Some(v) = get_str(o, key) {
                if !v.is_empty() && !TIERS.contains(&v.as_str()) {
                    return Err(format!("{gid}: unknown tier {v:?} (use one of {TIERS:?})"));
                }
            }
        }
        let mut hle = get_str(o, "hle").unwrap_or_else(|| "not run".into());
        let mut bios = get_str(o, "bios").unwrap_or_else(|| "not run".into());
        let issue_list: Vec<String> = o
            .get("issues")
            .and_then(toml::Value::as_array)
            .map(|a| a.iter().map(display).collect())
            .unwrap_or_default();
        let mut issues = if issue_list.is_empty() {
            "none known".to_string()
        } else {
            issue_list.join("; ")
        };
        let mut same = "-".to_string();
        let mut commit = get_str(o, "measured_on").unwrap_or_else(|| "-".into());
        if let Some(Run {
            result: r,
            commit: report_commit,
        }) = found
        {
            if r.get("status").and_then(Value::as_str) == Some("ran") {
                let reference_row = table(&reference, &gid).unwrap_or(&empty);
                let ref_hash = get_str(reference_row, "bios_final_hash").unwrap_or_default();
                let ref_frames = reference_row
                    .get("frames")
                    .and_then(toml::Value::as_integer);
                let run_frames = r.get("frames").and_then(Value::as_i64);
                if !ref_hash.is_empty() && ref_frames == run_frames {
                    let display_hash = r.get("display_hash").map(json_display);
                    same = if display_hash.as_deref() == Some(ref_hash.as_str()) {
                        "yes"
                    } else {
                        "no"
                    }
                    .into();
                }
                if truthy(r.get("first_unimplemented")) {
                    let full = json_display(&r["first_unimplemented"]);
                    let name = full.split(" a0=").next().unwrap_or("");
                    let _ = write!(issues, "; first unimplemented BIOS call {name}");
                }
                if truthy(r.get("cd_sectors_dropped")) {
                    let _ = write!(
                        issues,
                        "; {} CD sectors lost (HLE run)",
                        json_display(&r["cd_sectors_dropped"])
                    );
                }
                if !o.is_empty() {
                    let judged = o.get("hle_hash").map(display);
                    let now = r.get("display_hash").map(json_display);
                    if judged != now {
                        notes.push(gid.clone());
                        hle.push_str(" (re-check: result changed)");
                    }
                }
                if let Some(c) = report_commit {
                    commit = c.clone();
                }
            } else {
                let status = r
                    .get("status")
                    .map_or_else(|| "not run".to_string(), json_display);
                hle = status.clone();
                bios = status;
                if truthy(r.get("detail")) {
                    let _ = write!(issues, "; {}", json_display(&r["detail"]));
                }
            }
        }
        if let Some(Run { result: r, .. }) = found {
            let no_sbi = r.get("sbi_sectors").is_none_or(Value::is_null);
            let libcrypt = o.get("libcrypt").is_some_and(|v| match v {
                toml::Value::Boolean(b) => *b,
                toml::Value::Integer(i) => *i != 0,
                toml::Value::String(s) => !s.is_empty(),
                _ => true,
            });
            if no_sbi && libcrypt {
                issues.push_str("; LibCrypt disc, no .sbi next to it");
            }
        }
        let thumb = format!("images/games/{gid}.png");
        let shot = if root.join("docs").join(&thumb).exists() {
            format!("<img src=\"{thumb}\" width=\"96\" alt=\"\">")
        } else {
            String::new()
        };
        let cells = [
            get_str(g, "title").unwrap_or_else(|| gid.clone()),
            get_str(g, "serial").unwrap_or_else(|| "-".into()),
            get_str(g, "region").unwrap_or_else(|| "-".into()),
            hle,
            bios,
            get_str(o, "fmv").unwrap_or_else(|| "-".into()),
            issues,
            same,
            commit,
            get_str(o, "evidence").unwrap_or_else(|| "-".into()),
        ];
        let joined: Vec<String> = cells.iter().map(|c| cell(c)).collect();
        rows.push(format!("| {shot} | {} |", joined.join(" | ")));
    }

    let recorded: BTreeSet<String> = reference
        .values()
        .map(|v| {
            v.as_table()
                .and_then(|t| get_str(t, "recorded_on"))
                .unwrap_or_else(|| "?".into())
        })
        .collect();
    let join_or_unknown = |set: &BTreeSet<String>| {
        if set.is_empty() {
            "?".to_string()
        } else {
            set.iter().cloned().collect::<Vec<_>>().join(", ")
        }
    };
    let mut text = HEADER
        .replace("{commits}", &join_or_unknown(&commits))
        .replace("{ref_commits}", &join_or_unknown(&recorded));
    text.push_str("\n## Commercial discs\n\n");
    text.push_str(COLUMNS);
    text.push('\n');
    let separators = vec!["---"; COLUMNS.matches('|').count() - 1];
    let _ = writeln!(text, "|{}|", separators.join("|"));
    text.push_str(&rows.join("\n"));
    text.push('\n');
    if let Some(extra) = table(&obs, "_notes")
        .and_then(|n| get_str(n, "text"))
        .filter(|t| !t.is_empty())
    {
        text.push_str("\n## Notes\n\n");
        text.push_str(extra.trim());
        text.push('\n');
    }
    if !notes.is_empty() {
        let _ = write!(
            text,
            "\nRe-check: the last frame of {} differs from the run the tier was judged on.\n",
            notes.join(", ")
        );
    }
    fs::write(out, text).map_err(|e| format!("{}: {e}", out.display()))?;
    Ok(format!(
        "wrote {}: {} games, {} to re-check",
        out.display(),
        rows.len(),
        notes.len()
    ))
}

fn main() -> ExitCode {
    let mut root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let mut out: Option<PathBuf> = None;
    let mut inputs: Vec<String> = Vec::new();
    let mut args = std::env::args().skip(1);
    while let Some(a) = args.next() {
        match a.as_str() {
            "--out" => out = args.next().map(PathBuf::from),
            "--root" => {
                if let Some(r) = args.next() {
                    root = PathBuf::from(r);
                }
            }
            _ => inputs.push(a),
        }
    }
    if inputs.is_empty() {
        eprintln!(
            "usage: compat-report <report.json|dir> [...] [--out docs/COMPATIBILITY.md] [--root <repo>]"
        );
        return ExitCode::FAILURE;
    }
    let out = out.unwrap_or_else(|| root.join("docs/COMPATIBILITY.md"));
    match run(&inputs, &out, &root) {
        Ok(line) => {
            println!("{line}");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("{e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cells_escape_pipes_and_newlines() {
        assert_eq!(cell("a|b\nc"), "a\\|b c");
    }

    #[test]
    fn truthiness_matches_the_report_conventions() {
        assert!(!truthy(None));
        assert!(!truthy(Some(&Value::from(0))));
        assert!(!truthy(Some(&Value::from(""))));
        assert!(truthy(Some(&Value::from(3))));
        assert!(truthy(Some(&Value::from("x"))));
    }

    #[test]
    fn separator_row_has_one_dash_cell_per_column() {
        // 11 columns: 12 pipes in the header row.
        assert_eq!(COLUMNS.matches('|').count() - 1, 11);
    }
}
