#!/usr/bin/env python3
"""Regenerate docs/COMPATIBILITY.md from compat runs.

Inputs:

* compat/games.toml         facts per disc (title, serial, region, hashes)
* compat/observations.toml  human judgement per disc: status tier with and
                            without a BIOS, FMV status, known issues, the
                            evidence behind them, and the final display
                            hashes of the run they were judged on
* one or more hle_compat --json reports (files or directories of them),
  normally a full `hle_compat --reference` run

The runner measures what a machine can: whether the boot reached the
executable, how far it ran, the first unimplemented BIOS call, whether the
last frame matches the real-BIOS run, MDEC work, lost sectors, LibCrypt
subchannel data. Tiers need someone to look at frames, so they come from
observations.toml; when a new run's final display differs from the one a
tier was judged on, the table says the tier needs another look instead of
silently keeping it.

usage: compat_report.py <report.json|dir> [...] [--out docs/COMPATIBILITY.md]
"""

import json
import os
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TIERS = ["none", "boots", "intro", "menu", "in-game", "playable", "perfect"]

HEADER = """# Compatibility

What runs on PSoXide, with no BIOS (the built-in HLE kernel) and, for
comparison, with a real BIOS. Generated by `tools/compat_report.py` from
`compat/games.toml`, `compat/observations.toml` and an `hle_compat` run;
edit those, not this file. Game names and results only: no game data or
images live in this repository.

## Status tiers

| Tier | Meaning |
|---|---|
| none | Nothing useful on screen (black or a hang before the first picture). |
| boots | Reaches the game's executable and draws something of its own. |
| intro | Logos, legal screens, FMV or attract mode play. |
| menu | Title screen or menus respond to input. |
| in-game | Gameplay (or the game's own engine running past its menus, such as an opening cutscene after New Game) is reached with scripted input. |
| playable | Played through a real stretch by a person without game-breaking problems. |
| perfect | Played through with no known problems. |

Headless runs can show at most **in-game**: they press Start and Cross on a
fixed schedule and look at frames. **playable** and **perfect** need a
person (evidence "Manny, console" or "Manny, GUI").

FMV: **plays** (movies decode and show), **partial** (some movies or frames
missing), **broken**, **none seen** (none reached in the run), **n/a** (the
game has none).

## How the runs are made

`hle_compat --inputs compat/inputs.toml` boots each disc from the
executable's entry with a formatted empty memory card, a digital pad and no
frame limiter, for the run length and pad schedule `compat/inputs.toml`
gives it (games without one: Start at frame 600, Cross at 750, alternating
every 150 frames to 3450, for 3600 frames). The "real BIOS" column is the
same run through the developer's own BIOS dump (dev-only `--reference`),
counted from the same point. Frames were looked at for every tier below.

Run on: {commits}
"""

COLUMNS = (
    "| Game | Serial | Region | No BIOS (HLE) | Real BIOS | FMV | Known issues | "
    "Last frame = BIOS | Measured on | Evidence |"
)


def load_toml(path):
    with open(path, "rb") as f:
        return tomllib.load(f)


def load_reports(paths):
    results, commits, frames = {}, set(), set()
    files = []
    for p in paths:
        if os.path.isdir(p):
            files += sorted(
                os.path.join(p, n) for n in os.listdir(p) if n.endswith(".json")
            )
        else:
            files.append(p)
    for f in files:
        with open(f) as fh:
            report = json.load(fh)
        if not str(report.get("schema", "")).startswith("psoxide-hle-compat/"):
            continue
        if report.get("emulator_commit"):
            commits.add(report["emulator_commit"])
        frames.add(report.get("frames"))
        for r in report.get("results", []):
            if r.get("status") == "missing":
                continue
            results[r["id"]] = (r, report)
    return results, commits, frames


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def main(argv):
    out = os.path.join(ROOT, "docs", "COMPATIBILITY.md")
    inputs = []
    it = iter(argv)
    for a in it:
        if a == "--out":
            out = next(it)
        else:
            inputs.append(a)
    if not inputs:
        sys.exit(__doc__)
    games = load_toml(os.path.join(ROOT, "compat", "games.toml")).get("game", [])
    obs = load_toml(os.path.join(ROOT, "compat", "observations.toml"))
    results, commits, frames = load_reports(inputs)

    rows = []
    notes = []
    for g in games:
        gid = g["id"]
        o = obs.get(gid, {})
        r, report = results.get(gid, (None, None))
        for key in ("hle", "bios"):
            if o.get(key) and o[key] not in TIERS:
                sys.exit(f"{gid}: unknown tier {o[key]!r} (use one of {TIERS})")
        hle, bios = o.get("hle", "not run"), o.get("bios", "not run")
        issues = "; ".join(o.get("issues", [])) or "none known"
        same = "-"
        commit = o.get("measured_on", "-")
        if r is not None and r.get("status") == "ran":
            ref = r.get("reference") or {}
            if ref.get("display_hash"):
                same = "yes" if ref["display_hash"] == r.get("display_hash") else "no"
            if r.get("first_unimplemented"):
                name = r["first_unimplemented"].split(" a0=")[0]
                issues += f"; first unimplemented BIOS call {name}"
            if r.get("cd_sectors_dropped"):
                issues += f"; {r['cd_sectors_dropped']} CD sectors lost (HLE run)"
            judged = (o.get("hle_hash"), o.get("bios_hash"))
            now = (r.get("display_hash"), ref.get("display_hash"))
            if o and judged != now:
                notes.append(gid)
                hle += " (re-check: result changed)"
            commit = report.get("emulator_commit") or commit
        elif r is not None:
            hle = bios = r.get("status", "not run")
            if r.get("detail"):
                issues += f"; {r['detail']}"
        if r is not None and r.get("sbi_sectors") is None and o.get("libcrypt"):
            issues += "; LibCrypt disc, no .sbi next to it"
        rows.append(
            "| "
            + " | ".join(
                cell(x)
                for x in (
                    g.get("title", gid),
                    g.get("serial", "-"),
                    g.get("region", "-"),
                    hle,
                    bios,
                    o.get("fmv", "-"),
                    issues,
                    same,
                    commit,
                    o.get("evidence", "-"),
                )
            )
            + " |"
        )

    text = HEADER.format(
        frames="/".join(str(f) for f in sorted(x for x in frames if x)) or "?",
        commits=", ".join(sorted(commits)) or "?",
    )
    text += "\n## Commercial discs\n\n" + COLUMNS + "\n"
    text += "|" + "|".join("---" for _ in range(COLUMNS.count("|") - 1)) + "|\n"
    text += "\n".join(rows) + "\n"
    extra = obs.get("_notes", {}).get("text")
    if extra:
        text += "\n## Notes\n\n" + extra.strip() + "\n"
    if notes:
        text += (
            "\nRe-check: the last frame of "
            + ", ".join(notes)
            + " differs from the run the tier was judged on.\n"
        )
    with open(out, "w") as f:
        f.write(text)
    print(f"wrote {out}: {len(rows)} games, {len(notes)} to re-check")


if __name__ == "__main__":
    main(sys.argv[1:])
